/* eslint-disable @next/next/no-sync-scripts */
import Counter from "@/components/Counter";
import DynamicCounter from "@/components/DynamicCounter";
import HooksCounter from "@/components/HooksCounter";
import VariableCounter from "@/components/VariableCounter";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Todo | Redux Fundamental Example</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <section>
        <div className="w-screen h-screen p-10 bg-gray-100 text-slate-700">
          <h1 className="max-w-md mx-auto text-center text-2xl font-bold">
            Simple Counter Application
          </h1>

          <div className="max-w-md mx-auto mt-10 space-y-5">
            <p>Static Counter</p>
            <HooksCounter />
            <p>Dynamic Counter</p>
            <DynamicCounter id="474070" />
            <p>normal variable Counter</p>
            <VariableCounter />
            <p>Variable counter with own props</p>
            <VariableCounter dynamic />
          </div>
        </div>
      </section>
    </>
  );
}
